### ISSUE TITLE
Allow script tags

### ISSUE THREAD

**Issue by FedeltaMedia** [magefan/module-wysiwyg-advanced#5] opened 2020-02-06 12:03 UTC
Is there a way to allow script tags inside CMS pages? Some social buttons for example come with ready to copy-paste <script> tags to allow these on certain pages.

I've tried this, but it didn't seem to work. The editor removes the tags once the editor loads again:
```
$settings['extended_valid_elements'] = '+script[*]';
$settings['valid_children'] = '+body[style|script]';
```

**Comment by LiamKarlMitchell** [comment] 2020-02-13 06:52
Hi @Fidelity88 ,

Duplicate of https://github.com/magefan/module-wysiwyg-advanced/issues/2

**Closed as completed** 2020-04-29 04:13 UTC
